// Optional browser QA. npm's Playwright package + a Chromium executable are required.
// They are development dependencies only; readers and builders need neither.
const assert = require("node:assert/strict");
const path = require("node:path");
const { pathToFileURL } = require("node:url");
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({
    headless: true,
    ...(process.env.CHROME_BIN ? {executablePath: process.env.CHROME_BIN} : {}),
  });
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
    const errors = [], requests = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("request", request => {if (/^https?:/.test(request.url())) requests.push(request.url());});
    const url = pathToFileURL(path.resolve(__dirname, "../index.html")).href;
    await page.goto(url);
    assert.equal(await page.locator(".card").count(), 60);
    assert.equal(await page.locator("#filters").isVisible(), true);
    assert.equal(await page.locator(".argument").count(), 11);
    assert.equal(await page.locator(".playbook").count(), 10);
    assert.equal(await page.locator(".chapter-intro").count(), 32);
    await page.goto(url + "#e11");
    await page.waitForFunction(() => document.getElementById("e11").open);
    assert.equal(await page.locator("#e11 .prose table tbody tr").count(), 4);
    await page.locator("#e11 a[href='#pleasure-virtual']").click();
    assert.equal(new URL(page.url()).hash, "#pleasure-virtual");
    assert(await page.locator("#e11 .prose").isVisible());
    await page.locator("#e11 a[href='#f27']").first().click();
    await page.waitForFunction(() => document.getElementById("f27").open);
    assert.match(await page.locator("#f27 .prose").textContent(), /没有直接核读/);
    await page.locator("#f27 a[href='#e11']").click();
    await page.waitForFunction(() => document.getElementById("e11").open);
    await page.goto(url + "#e01");
    await page.waitForFunction(() => document.getElementById("e01").open);
    await page.locator("#e01 a[href='#e11']").click();
    assert.equal(new URL(page.url()).hash, "#e11");
    await page.locator("#chapter-query").fill("C02");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.locator("#chapter-query").fill("套餐 风味");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.locator("#chapter-query").fill("不存在的章节87765");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 0);
    await page.goto(url + "#c03");
    await page.waitForFunction(() => document.getElementById("c03").open);
    assert.equal(await page.locator("#chapter-query").inputValue(), "");
    assert.match(await page.locator("#c03 .prose").textContent(), /新鲜感，不是生活不及格后的补考/);
    await page.goto(url + "#c06");
    await page.waitForFunction(() => document.getElementById("c06").open);
    assert.equal(await page.locator("#c06 .prose table").count(), 1);
    await page.goto(url + "#c08");
    await page.waitForFunction(() => document.getElementById("c08").open);
    await page.locator("#c08 a[href='#n05']").click();
    await page.waitForFunction(() => document.getElementById("n05").open);
    assert.match(await page.locator("#n05 .prose").textContent(), /p = \.053/);
    assert.match(await page.locator("#n05 .prose").textContent(), /p = \.84/);
    await page.goto(url + "#c07");
    await page.waitForFunction(() => document.getElementById("c07").open);
    await page.locator("#c07 a[href='#n06']").click();
    await page.waitForFunction(() => document.getElementById("n06").open);
    assert.match(await page.locator("#n06 .prose").textContent(), /p = \.032/);
    await page.goto(url + "#c09");
    await page.waitForFunction(() => document.getElementById("c09").open);
    await page.locator("#c09 a[href='#f01']").click();
    await page.waitForFunction(() => document.getElementById("f01").open);
    assert.match(await page.locator("#f01 .prose").textContent(), /不是每个人连续记了七天/);
    await page.goto(url + "#c10");
    await page.waitForFunction(() => document.getElementById("c10").open);
    assert.match(await page.locator("#c10 .prose").textContent(), /“那一刻很好”与“整个安排不值得”/);
    await page.locator("#chapter-query").fill("C12");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c12");
    await page.waitForFunction(() => document.getElementById("c12").open);
    assert.match(await page.locator("#c12 .prose").textContent(), /长镜头说的是镜头持续/);
    assert.equal(await page.locator("#c12 .prose table").count(), 3);
    assert.equal(await page.locator("#c12 .artwork img").count(), 3);
    assert.equal(await page.locator("#c12 .prose details").getAttribute("open"), null);
    assert.equal(await page.locator("#c12 .prose details img").isVisible(), false);
    await page.locator("#c12 .prose details > summary").click();
    for (const image of await page.locator("#c12 .artwork img").all()) {
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert.ok(await image.evaluate(img => img.naturalWidth > 0 && img.alt.length > 30));
    }
    await page.locator("#c12 .prose details > summary").click();
    await page.locator("#c12 a[href='#f16']").first().click();
    await page.waitForFunction(() => document.getElementById("f16").open);
    assert.match(await page.locator("#f16 .prose").textContent(), /不是连续完整播放/);
    await page.goto(url + "#c12");
    await page.locator("#c12 a[href='#f03']").click();
    await page.waitForFunction(() => document.getElementById("f03").open);
    assert.match(await page.locator("#f03 .prose").textContent(), /实际依据是条目的文字解释/);
    await page.goto(url + "#c11");
    await page.waitForFunction(() => document.getElementById("c11").open);
    assert.equal(await page.locator("#c11 .artwork img").count(), 2);
    for (const image of await page.locator("#c11 .artwork img").all()) {
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert.ok(await image.evaluate(img => img.naturalWidth > 0 && img.alt.length > 30));
    }
    await page.screenshot({path: "/tmp/enjoythemoment-music-desktop.png", fullPage: false});
    await page.locator("#c11 a[href='#f15']").first().click();
    await page.waitForFunction(() => document.getElementById("f15").open);
    assert.match(await page.locator("#f15 .prose").textContent(), /没有实际试听/);
    await page.goto(url + "#c13");
    await page.waitForFunction(() => document.getElementById("c13").open);
    await page.locator("#c13 a[href='#f04']").click();
    await page.waitForFunction(() => document.getElementById("f04").open);
    assert.match(await page.locator("#f04 .prose").textContent(), /技术标准 PDF 本次未能成功获取/);
    await page.goto(url + "#c14");
    await page.waitForFunction(() => document.getElementById("c14").open);
    await page.locator("#c14 a[href='#f05']").first().click();
    await page.waitForFunction(() => document.getElementById("f05").open);
    assert.match(await page.locator("#f05 .prose").textContent(), /没有进行盲品/);
    await page.locator("#chapter-query").fill("C15");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c15");
    await page.waitForFunction(() => document.getElementById("c15").open);
    await page.locator("#c15 a[href='#f06']").click();
    await page.waitForFunction(() => document.getElementById("f06").open);
    assert.match(await page.locator("#f06 .prose").textContent(), /没有实地评估任何街区/);
    await page.goto(url + "#e02");
    await page.waitForFunction(() => document.getElementById("e02").open);
    await page.locator("#e02 a[href='#n03']").click();
    await page.waitForFunction(() => document.getElementById("n03").open);
    assert.match(await page.locator("#n03 .prose").textContent(), /德国为 49.7%/);
    await page.goto(url + "#c01");
    await page.waitForFunction(() => document.getElementById("c01").open);
    assert.match(await page.locator("#c01 .prose").textContent(), /想要一个晚上，别总被劝成五分钟/);
    await page.locator("#chapter-query").fill("C16");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c16");
    await page.waitForFunction(() => document.getElementById("c16").open);
    assert.match(await page.locator("#c16 .prose").textContent(), /镜子里的合适，与身体里的合适/);
    for (const [chapter, anchor, evidence] of [
      ["c14", "flavor-ice-cream", "f25"],
      ["c16", "dress-form-examples", "f26"],
    ]) {
      await page.goto(url + "#" + chapter);
      await page.locator("#" + chapter + " a[href='#" + anchor + "']").click();
      assert.equal(new URL(page.url()).hash, "#" + anchor);
      assert(await page.locator("#" + chapter + " .prose").isVisible());
      const image = page.locator("#" + chapter + " .artwork img");
      assert.equal(await image.count(), 1);
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert.equal(await image.evaluate(img => img.naturalWidth), 880);
      await page.screenshot({path: "/tmp/enjoythemoment-" + chapter + "-detail-desktop.png", fullPage: false});
      await page.locator("#" + chapter + " a[href='#" + evidence + "']").first().click();
      await page.waitForFunction(id => document.getElementById(id).open, evidence);
    }
    assert.match(await page.locator("#f26 .prose").textContent(), /未独立核对销售账册/);
    await page.goto(url + "#c16");
    await page.locator("#c16 a[href='#f08']").click();
    await page.waitForFunction(() => document.getElementById("f08").open);
    assert.match(await page.locator("#f08 .prose").textContent(), /没有取得并完整审核 ISO 标准原文/);
    await page.goto(url + "#c17");
    await page.waitForFunction(() => document.getElementById("c17").open);
    await page.locator("#c17 a[href='#b07']").click();
    await page.waitForFunction(() => document.getElementById("research-content").open);
    await page.locator("#research-content a[href='#n07']").click();
    await page.waitForFunction(() => document.getElementById("n07").open);
    assert.match(await page.locator("#n07 .prose").textContent(), /不是长期幸福或整个制作过程的愉快程度/);
    await page.goto(url + "#c18");
    await page.waitForFunction(() => document.getElementById("c18").open);
    await page.locator("#c18 a[href='#n08']").click();
    await page.waitForFunction(() => document.getElementById("n08").open);
    assert.match(await page.locator("#n08 .prose").textContent(), /实际享受的交互 F < 1/);
    await page.locator("#chapter-query").fill("C19");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c19");
    await page.waitForFunction(() => document.getElementById("c19").open);
    assert.match(await page.locator("#c19 .prose").textContent(), /输赢与选择质量，可以分开看/);
    await page.locator("#c19 a[href='#f09']").click();
    await page.waitForFunction(() => document.getElementById("f09").open);
    await page.goto(url + "#c19");
    await page.locator("#c19 a[href='#n09']").click();
    await page.waitForFunction(() => document.getElementById("n09").open);
    assert.match(await page.locator("#n09 .prose").textContent(), /不是 38,935 人都完成三轮/);
    await page.goto(url + "#c20");
    await page.waitForFunction(() => document.getElementById("c20").open);
    await page.locator("#c20 a[href='#f10']").first().click();
    await page.waitForFunction(() => document.getElementById("f10").open);
    await page.goto(url + "#c20");
    await page.locator("#c20 a[href='#n10']").click();
    await page.waitForFunction(() => document.getElementById("n10").open);
    assert.match(await page.locator("#n10 .prose").textContent(), /p = .058/);
    await page.locator("#chapter-query").fill("C21");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c21");
    await page.waitForFunction(() => document.getElementById("c21").open);
    assert.match(await page.locator("#c21 .prose").textContent(), /让事情发生，和让发生的过程更舒服/);
    await page.locator("#c21 a[href='#n11']").click();
    await page.waitForFunction(() => document.getElementById("n11").open);
    assert.match(await page.locator("#n11 .prose").textContent(), /49.3%/);
    assert.match(await page.locator("#n11 .prose").textContent(), /p = .06/);
    await page.goto(url + "#c22");
    await page.waitForFunction(() => document.getElementById("c22").open);
    assert.match(await page.locator("#c22 .prose").textContent(), /奥斯汀的第一句话/);
    assert.equal(await page.locator("#c22 .prose table").count(), 1);
    await page.locator("#c22 a[href='#f11']").click();
    await page.waitForFunction(() => document.getElementById("f11").open);
    assert.match(await page.locator("#f11 .prose").textContent(), /社区整理的原作转录/);
    await page.locator("#chapter-query").fill("C23");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c23");
    await page.waitForFunction(() => document.getElementById("c23").open);
    assert.equal(await page.locator("#c23 .prose table").count(), 2);
    assert.match(await page.locator("#c23 .prose").textContent(), /310 分钟/);
    await page.locator("#c23 a[href='#n12']").click();
    await page.waitForFunction(() => document.getElementById("n12").open);
    assert.match(await page.locator("#n12 .prose").textContent(), /不是把同一批人逐日追踪八周/);
    await page.goto(url + "#c23");
    await page.locator("#c23 a[href='#f12']").click();
    await page.waitForFunction(() => document.getElementById("f12").open);
    assert.match(await page.locator("#f12 .prose").textContent(), /不能被拼接成该来源支持随意离队/);
    await page.goto(url + "#c24");
    await page.waitForFunction(() => document.getElementById("c24").open);
    assert.match(await page.locator("#c24 .prose").textContent(), /我家的书架已经很有文化了/);
    await page.locator("#c24 a[href='#n13']").click();
    await page.waitForFunction(() => document.getElementById("n13").open);
    assert.match(await page.locator("#n13 .prose").textContent(), /方法报 73 名大学生/);
    await page.locator("#chapter-query").fill("C25");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c25");
    await page.waitForFunction(() => document.getElementById("c25").open);
    assert.equal(await page.locator("#c25 .artwork img").count(), 3);
    for (const image of await page.locator("#c25 .artwork img").all()) {
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert.ok(await image.evaluate(img => img.naturalWidth > 0 && img.alt.length > 30));
    }
    await page.locator("#c25 a[href='#f13']").first().click();
    await page.waitForFunction(() => document.getElementById("f13").open);
    assert.match(await page.locator("#f13 .prose").textContent(), /1926.417/);
    await page.goto(url + "#c26");
    await page.waitForFunction(() => document.getElementById("c26").open);
    assert.match(await page.locator("#c26 > summary").textContent(), /永远差最后一件/);
    await page.locator("#c26 a[href='#f14']").first().click();
    await page.waitForFunction(() => document.getElementById("f14").open);
    assert.match(await page.locator("#f14 .prose").textContent(), /不是藏品鉴定/);
    await page.locator("#chapter-query").fill("C27");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c27");
    await page.waitForFunction(() => document.getElementById("c27").open);
    assert.equal(await page.locator("#c27 .prose table").count(), 2);
    assert.match(await page.locator("#c27 .prose").textContent(), /一段动作，不只由姿势组成/);
    await page.locator("#c27 a[href='#f17']").first().click();
    await page.waitForFunction(() => document.getElementById("f17").open);
    assert.match(await page.locator("#f17 .prose").textContent(), /没有观看并核验完整演出/);
    await page.goto(url + "#c28");
    await page.waitForFunction(() => document.getElementById("c28").open);
    assert.equal(await page.locator("#c28 .prose table").count(), 2);
    const offside = page.locator("#c28 .artwork img");
    await offside.scrollIntoViewIfNeeded();
    await offside.evaluate(img => img.decode());
    assert.ok(await offside.evaluate(img => img.naturalWidth > 0 && img.alt.length > 30));
    assert.ok(await offside.evaluate(img => img.getBoundingClientRect().width <= 440));
    await page.screenshot({path: "/tmp/enjoythemoment-sport-desktop.png", fullPage: false});
    await page.locator("#c28 a[href='#f18']").first().click();
    await page.waitForFunction(() => document.getElementById("f18").open);
    assert.match(await page.locator("#f18 .prose").textContent(), /位置本身不是犯规/);
    await page.goto(url + "#c28");
    await page.locator("#c28 a[href='#f19']").first().click();
    await page.waitForFunction(() => document.getElementById("f19").open);
    assert.match(await page.locator("#f19 .prose").textContent(), /生效日尚未到来/);
    await page.locator("#chapter-query").fill("C29");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c29");
    await page.waitForFunction(() => document.getElementById("c29").open);
    assert.equal(await page.locator("#c29 .prose table").count(), 2);
    assert.match(await page.locator("#c29 .prose").textContent(), /多数纬度/);
    await page.locator("#c29 .prose table").first().scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-sky-desktop.png", fullPage: false});
    await page.locator("#c29 a[href='#f21']").first().click();
    await page.waitForFunction(() => document.getElementById("f21").open);
    assert.match(await page.locator("#f21 .prose").textContent(), /没有教读者选购、安装、自制或检验太阳滤镜/);
    await page.goto(url + "#c30");
    await page.waitForFunction(() => document.getElementById("c30").open);
    assert.equal(await page.locator("#chapter-query").inputValue(), "");
    assert.equal(await page.locator("#c30 .prose table").count(), 2);
    assert.match(await page.locator("#c30 .prose").textContent(), /不是你所在城市的鸟类名录/);
    await page.locator("#c30 a[href='#f22']").first().click();
    await page.waitForFunction(() => document.getElementById("f22").open);
    assert.match(await page.locator("#f22 .prose").textContent(), /没有逐张目视核验照片/);
    await page.goto(url + "#c30");
    await page.locator("#c30 a[href='#f23']").first().click();
    await page.waitForFunction(() => document.getElementById("f23").open);
    assert.match(await page.locator("#f23 .prose").textContent(), /圈养鸟类另有边界/);
    await page.locator("#chapter-query").fill("C31");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c31");
    await page.waitForFunction(() => document.getElementById("c31").open);
    const fearSpoiler = page.locator("#c31 .prose details");
    assert.equal(await fearSpoiler.count(), 1);
    assert.equal(await fearSpoiler.getAttribute("open"), null);
    assert.match(await fearSpoiler.locator("summary").textContent(), /重大剧透/);
    assert.equal(await fearSpoiler.locator("p").first().isVisible(), false);
    await fearSpoiler.locator("summary").focus();
    await page.keyboard.press("Enter");
    assert(await fearSpoiler.locator("p").first().isVisible());
    assert.match(await fearSpoiler.textContent(), /没有直接交代第三个愿望的具体措辞/);
    await fearSpoiler.locator("p").first().scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-fear-desktop.png", fullPage: false});
    await fearSpoiler.locator("summary").click();
    await page.locator("#c31 a[href='#n15']").first().click();
    await page.waitForFunction(() => document.getElementById("n15").open);
    assert.match(await page.locator("#n15 .prose").textContent(), /p = \.564/);
    await page.goto(url + "#c31");
    await page.locator("#c31 a[href='#f24']").first().click();
    await page.waitForFunction(() => document.getElementById("f24").open);
    assert.equal(await page.locator("#f24 .prose details").getAttribute("open"), null);
    assert.equal(await page.locator("#f24 .prose details p").first().isVisible(), false);
    await page.goto(url + "#c32");
    await page.waitForFunction(() => document.getElementById("c32").open);
    assert.equal(await page.locator("#chapter-query").inputValue(), "");
    const hints = page.locator("#c32 .prose details");
    assert.equal(await hints.count(), 4);
    for (const hint of await hints.all()) assert.equal(await hint.getAttribute("open"), null);
    await hints.nth(0).locator("summary").click();
    assert(await hints.nth(0).locator("p").first().isVisible());
    assert.equal(await hints.nth(2).locator("p").first().isVisible(), false);
    await hints.nth(1).locator("summary").click();
    assert.equal(await hints.nth(2).locator("p").first().isVisible(), false);
    await hints.nth(2).locator("summary").click();
    assert.match(await hints.nth(2).textContent(), /伞、地图、船、月亮/);
    assert.equal(await hints.nth(3).locator("p").first().isVisible(), false);
    await page.locator("#c32 a[href='#n16']").first().click();
    await page.waitForFunction(() => document.getElementById("n16").open);
    assert.match(await page.locator("#n16 .prose").textContent(), /不是所有顿悟中有 37%/);
    await page.locator("#essay-query").fill("E10");
    assert.equal(await page.locator(".argument:visible").count(), 1);
    await page.goto(url + "#e10");
    await page.waitForFunction(() => document.getElementById("e10").open);
    assert.equal(await page.locator("#e10 .prose table").count(), 1);
    assert.match(await page.locator("#e10 .prose").textContent(), /开始、继续、再次回来/);
    await page.locator("#e10 .prose table").scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-attention-desktop.png", fullPage: false});
    await page.locator("#e10 a[href='#b14']").first().click();
    await page.waitForFunction(() => document.getElementById("research-content").open);
    assert.equal(new URL(page.url()).hash, "#b14");
    assert.match(await page.locator("#b14 + h3").textContent(), /暗黑模式的存在/);
    assert(await page.locator("#b14 + h3").isVisible());
    await page.goto(url + "#e10");
    await page.locator("#e10 a[href='#n14']").first().click();
    await page.waitForFunction(() => document.getElementById("n14").open);
    assert.match(await page.locator("#n14 .prose").textContent(), /不是对 11,286 名消费者的实验/);
    await page.goto(url + "#e10");
    await page.locator("#e10 a[href='#f20']").first().click();
    await page.waitForFunction(() => document.getElementById("f20").open);
    assert.match(await page.locator("#f20 .prose").textContent(), /六至九个页面/);
    await page.locator("#essay-query").fill("E08");
    assert.equal(await page.locator(".argument:visible").count(), 1);
    await page.locator("#essay-query").fill("没有这个论点887765");
    assert.equal(await page.locator(".argument:visible").count(), 0);
    await page.goto(url + "#e07");
    await page.waitForFunction(() => document.getElementById("e07").open);
    assert.equal(await page.locator("#essay-query").inputValue(), "");
    await page.locator("#guide-query").fill("P010");
    assert.equal(await page.locator(".playbook:visible").count(), 1);
    await page.goto(url + "#p010");
    await page.waitForFunction(() => document.getElementById("p010").open);
    assert.equal(await page.locator("#p010 .prose details").count(), 4);
    assert.equal(await page.locator("#p010 .prose details[open]").count(), 0);
    await page.locator("#p010 .prose details > summary").first().click();
    assert.equal(await page.locator("#p010 .prose details[open]").count(), 1);
    await page.locator("#guide-query").fill("不存在的玩法887");
    await page.goto(url + "#p001");
    await page.waitForFunction(() => document.getElementById("p001").open);
    assert.equal(await page.locator("#guide-query").inputValue(), "");
    await page.goto(url + "#n04");
    await page.waitForFunction(() => document.getElementById("n04").open);
    await page.locator("#query").fill("J019");
    assert.equal(await page.locator(".card:visible").count(), 1);
    await page.locator("#query").fill("没有这个关键词987654");
    assert.equal(await page.locator(".card:visible").count(), 0);
    assert.equal(await page.locator("#random").isDisabled(), true);
    assert.equal(await page.locator("#empty").isVisible(), true);
    await page.locator("#reset").click();
    await page.locator("#minutes").selectOption("20");
    await page.locator("#budget").selectOption("0");
    await page.locator("#company").selectOption("solo");
    await page.locator("#energy").selectOption("low");
    const matching = await page.locator(".card:visible").evaluateAll(items => items.map(x => x.dataset));
    assert(matching.length > 0);
    matching.forEach(x => {
      assert(Number(x.minutes) <= 20 && Number(x.budget) === 0);
      assert(["solo", "either"].includes(x.company) && x.energy === "low");
    });
    await page.locator("#random").click();
    assert(await page.evaluate(() => document.activeElement.tagName === "SUMMARY"));
    await page.goto(url + "#j019");
    await page.waitForFunction(() => document.getElementById("j019").open);
    assert.equal(await page.locator("#j019").getAttribute("open"), "");
    await page.goto(url + "#b01");
    await page.waitForFunction(() => document.getElementById("research-content").open);
    assert.equal(await page.locator("#research-content").getAttribute("open"), "");
    await page.goto(url);
    await page.reload();
    await page.locator("#j019 > summary").focus();
    await page.keyboard.press("Enter");
    assert.equal(await page.locator("#j019").getAttribute("open"), "");
    await page.evaluate(() => scrollTo({top: 0, behavior: "instant"}));
    await page.screenshot({path: process.env.SCREENSHOT_DESKTOP || "/tmp/enjoythemoment-desktop.png", fullPage: false});
    await page.setViewportSize({width: 390, height: 844});
    await page.goto(url + "#e11");
    await page.waitForFunction(() => document.getElementById("e11").open);
    await page.locator("#e11 .prose table").scrollIntoViewIfNeeded();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path: "/tmp/enjoythemoment-pleasure-reality-mobile.png", fullPage: false});
    await page.goto(url + "#e10");
    await page.waitForFunction(() => document.getElementById("e10").open);
    await page.locator("#e10 .prose table").scrollIntoViewIfNeeded();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path: "/tmp/enjoythemoment-attention-mobile.png", fullPage: false});
    await page.goto(url);
    await page.reload();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.goto(url + "#e04");
    await page.waitForFunction(() => document.getElementById("e04").open);
    await page.locator("#e04").evaluate(el => el.scrollIntoView({behavior: "instant", block: "start"}));
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path: "/tmp/enjoythemoment-essay-mobile.png", fullPage: false});
    await page.goto(url + "#c25");
    await page.waitForFunction(() => document.getElementById("c25").open);
    const artImage = page.locator("#c25 .artwork img").first();
    await artImage.scrollIntoViewIfNeeded();
    await artImage.evaluate(img => img.decode());
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert(await artImage.evaluate(img => img.getBoundingClientRect().right <= innerWidth));
    await page.screenshot({path: "/tmp/enjoythemoment-art-mobile.png", fullPage: false});
    for (const id of ["c11", "c12"]) {
      await page.goto(url + "#" + id);
      await page.waitForFunction(id => document.getElementById(id).open, id);
      const image = page.locator("#" + id + " .artwork img").first();
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      assert(await image.evaluate(img => img.getBoundingClientRect().right <= innerWidth));
      await page.screenshot({path: "/tmp/enjoythemoment-" + id + "-mobile.png", fullPage: false});
    }
    for (const id of ["c14", "c16"]) {
      await page.goto(url + "#" + id);
      const image = page.locator("#" + id + " .artwork img");
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      assert(await image.evaluate(img => img.getBoundingClientRect().right <= innerWidth));
      await page.screenshot({path: "/tmp/enjoythemoment-" + id + "-detail-mobile.png", fullPage: false});
    }
    await page.locator("#c12 .prose details > summary").click();
    const ending = page.locator("#c12 .prose details img");
    await ending.scrollIntoViewIfNeeded();
    await ending.evaluate(img => img.decode());
    await page.screenshot({path: "/tmp/enjoythemoment-film-spoiler-mobile.png", fullPage: false});
    for (const id of ["c27", "c28", "c29", "c30"]) {
      await page.goto(url + "#" + id);
      await page.waitForFunction(id => document.getElementById(id).open, id);
      await page.locator("#" + id + " .prose table").first().scrollIntoViewIfNeeded();
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.screenshot({path: "/tmp/enjoythemoment-" + id + "-mobile.png", fullPage: false});
    }
    await page.goto(url + "#c30");
    await page.locator("#c30 .prose table").nth(1).scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-birds-mobile.png", fullPage: false});
    await page.goto(url + "#c29");
    await page.locator("#c29 .prose table").first().scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-sky-mobile.png", fullPage: false});
    for (const id of ["c31", "c32"]) {
      await page.goto(url + "#" + id);
      await page.waitForFunction(id => document.getElementById(id).open, id);
      await page.locator("#" + id + " .prose table").first().scrollIntoViewIfNeeded();
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.screenshot({path: "/tmp/enjoythemoment-" + id + "-mobile.png", fullPage: false});
    }
    await page.goto(url + "#c32");
    await page.locator("#c32 .prose details").nth(2).scrollIntoViewIfNeeded();
    await page.screenshot({path: "/tmp/enjoythemoment-puzzle-mobile.png", fullPage: false});
    const mobileOffside = page.locator("#c28 .artwork img");
    await mobileOffside.scrollIntoViewIfNeeded();
    await mobileOffside.evaluate(img => img.decode());
    assert(await mobileOffside.evaluate(img => img.getBoundingClientRect().right <= innerWidth));
    // This portrait diagram uses a 440-unit canvas and 22-unit minimum text.
    // Guard against returning to the illegible wide version; visual QA is still required.
    assert(await mobileOffside.evaluate(img => 22 * (img.getBoundingClientRect().width - 2) / 440 >= 16));
    await page.screenshot({path: "/tmp/enjoythemoment-offside-mobile.png", fullPage: false});
    await page.goto(url);
    await page.reload();
    await page.screenshot({path: process.env.SCREENSHOT_MOBILE || "/tmp/enjoythemoment-mobile.png", fullPage: false});
    await page.emulateMedia({colorScheme: "dark", reducedMotion: "reduce"});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.emulateMedia({media: "print"});
    await page.evaluate(() => dispatchEvent(new Event("beforeprint")));
    assert.equal(await page.locator("details:not([open])").count(), 0);
    assert.equal(errors.length, 0, JSON.stringify(errors));
    assert.equal(requests.length, 0, JSON.stringify(requests));
    const nojs = await browser.newContext({javaScriptEnabled: false, viewport: {width: 390, height: 844}});
    const staticPage = await nojs.newPage();
    await staticPage.goto(url);
    assert.equal(await staticPage.locator(".card").count(), 60);
    assert.equal(await staticPage.locator("#filters").isVisible(), false);
    assert.equal(await staticPage.locator("#essay-search-label").isVisible(), false);
    await staticPage.locator("#e07 > summary").click();
    assert.equal(await staticPage.locator("#e07 .prose").isVisible(), true);
    await staticPage.locator("#e10 > summary").click();
    assert.equal(await staticPage.locator("#e10 .prose").isVisible(), true);
    assert.match(await staticPage.locator("#e10 .prose").textContent(), /不是市场报价/);
    await staticPage.locator("#e11 > summary").click();
    assert.equal(await staticPage.locator("#e11 .prose").isVisible(), true);
    assert.match(await staticPage.locator("#e11 .prose").textContent(), /不是直接核读诺齐克原书/);
    await staticPage.locator("#f27 > summary").click();
    assert.equal(await staticPage.locator("#f27 .prose").isVisible(), true);
    assert.equal(await staticPage.locator("#f27 a[href='#e11']").count(), 1);
    await staticPage.locator("#j001 > summary").click();
    assert.equal(await staticPage.locator("#j001 .card-body").isVisible(), true);
    await staticPage.locator("#c25 > summary").click();
    assert.equal(await staticPage.locator("#c25 .artwork img").count(), 3);
    await staticPage.locator("#c25 .artwork img").first().scrollIntoViewIfNeeded();
    assert(await staticPage.locator("#c25 .artwork img").first().evaluate(img => img.complete && img.naturalWidth > 0));
    await staticPage.locator("#c12 > summary").click();
    assert.equal(await staticPage.locator("#c12 .prose details img").isVisible(), false);
    await staticPage.locator("#c12 .prose details > summary").click();
    await staticPage.locator("#c12 .prose details img").scrollIntoViewIfNeeded();
    await staticPage.locator("#c12 .prose details img").evaluate(img => img.decode());
    assert(await staticPage.locator("#c12 .prose details img").isVisible());
    await staticPage.locator("#c27 > summary").click();
    assert.match(await staticPage.locator("#c27 .prose").textContent(), /不加难|四格|四个问题/);
    await staticPage.locator("#c28 > summary").click();
    await staticPage.locator("#c28 .artwork img").scrollIntoViewIfNeeded();
    await staticPage.locator("#c28 .artwork img").evaluate(img => img.decode());
    assert(await staticPage.locator("#c28 .artwork img").isVisible());
    for (const id of ["c14", "c16"]) {
      await staticPage.locator("#" + id + " > summary").click();
      const image = staticPage.locator("#" + id + " .artwork img");
      await image.scrollIntoViewIfNeeded();
      await image.evaluate(img => img.decode());
      assert(await image.isVisible());
    }
    for (const id of ["c29", "c30"]) {
      await staticPage.locator(`#${id} > summary`).click();
      assert(await staticPage.locator(`#${id} .prose`).isVisible());
      assert.equal(await staticPage.locator(`#${id} .prose table`).count(), 2);
    }
    await staticPage.locator("#c31 > summary").click();
    assert.equal(await staticPage.locator("#c31 .prose details p").first().isVisible(), false);
    await staticPage.locator("#c31 .prose details > summary").click();
    assert(await staticPage.locator("#c31 .prose details p").first().isVisible());
    await staticPage.locator("#c32 > summary").click();
    const staticHints = staticPage.locator("#c32 .prose details");
    assert.equal(await staticHints.count(), 4);
    await staticHints.nth(0).locator("summary").click();
    assert(await staticHints.nth(0).locator("p").first().isVisible());
    assert.equal(await staticHints.nth(2).locator("p").first().isVisible(), false);
    await nojs.close();
    console.log("OK: offline, filters, empty state, deep links, keyboard, 390px, dark/reduced motion, print, no-JS, zero external requests");
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
