// Optional browser QA. npm's Playwright package + a Chromium executable are required.
// They are development dependencies only; readers and builders need neither.
const assert = require("node:assert/strict");
const path = require("node:path");
const { pathToFileURL } = require("node:url");
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({
    headless: true,
    ...(process.env.CHROME_BIN ? {executablePath: process.env.CHROME_BIN} : {}),
  });
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
    const errors = [], requests = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("request", request => {if (/^https?:/.test(request.url())) requests.push(request.url());});
    const url = pathToFileURL(path.resolve(__dirname, "../index.html")).href;
    await page.goto(url);
    assert.equal(await page.locator(".card").count(), 60);
    assert.equal(await page.locator("#filters").isVisible(), true);
    assert.equal(await page.locator(".argument").count(), 9);
    assert.equal(await page.locator(".playbook").count(), 10);
    assert.equal(await page.locator(".chapter-intro").count(), 20);
    await page.locator("#chapter-query").fill("C02");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.locator("#chapter-query").fill("套餐 风味");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.locator("#chapter-query").fill("不存在的章节87765");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 0);
    await page.goto(url + "#c03");
    await page.waitForFunction(() => document.getElementById("c03").open);
    assert.equal(await page.locator("#chapter-query").inputValue(), "");
    assert.match(await page.locator("#c03 .prose").textContent(), /新鲜感，不是生活不及格后的补考/);
    await page.goto(url + "#c06");
    await page.waitForFunction(() => document.getElementById("c06").open);
    assert.equal(await page.locator("#c06 .prose table").count(), 1);
    await page.goto(url + "#c08");
    await page.waitForFunction(() => document.getElementById("c08").open);
    await page.locator("#c08 a[href='#n05']").click();
    await page.waitForFunction(() => document.getElementById("n05").open);
    assert.match(await page.locator("#n05 .prose").textContent(), /p = \.053/);
    assert.match(await page.locator("#n05 .prose").textContent(), /p = \.84/);
    await page.goto(url + "#c07");
    await page.waitForFunction(() => document.getElementById("c07").open);
    await page.locator("#c07 a[href='#n06']").click();
    await page.waitForFunction(() => document.getElementById("n06").open);
    assert.match(await page.locator("#n06 .prose").textContent(), /p = \.032/);
    await page.goto(url + "#c09");
    await page.waitForFunction(() => document.getElementById("c09").open);
    await page.locator("#c09 a[href='#f01']").click();
    await page.waitForFunction(() => document.getElementById("f01").open);
    assert.match(await page.locator("#f01 .prose").textContent(), /不是每个人连续记了七天/);
    await page.goto(url + "#c10");
    await page.waitForFunction(() => document.getElementById("c10").open);
    assert.match(await page.locator("#c10 .prose").textContent(), /“那一刻很好”与“整个安排不值得”/);
    await page.locator("#chapter-query").fill("C12");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c12");
    await page.waitForFunction(() => document.getElementById("c12").open);
    assert.match(await page.locator("#c12 .prose").textContent(), /长镜头说的是镜头持续/);
    assert.equal(await page.locator("#c12 .prose table").count(), 2);
    await page.locator("#c12 a[href='#f03']").click();
    await page.waitForFunction(() => document.getElementById("f03").open);
    assert.match(await page.locator("#f03 .prose").textContent(), /实际依据是条目的文字解释/);
    await page.goto(url + "#c13");
    await page.waitForFunction(() => document.getElementById("c13").open);
    await page.locator("#c13 a[href='#f04']").click();
    await page.waitForFunction(() => document.getElementById("f04").open);
    assert.match(await page.locator("#f04 .prose").textContent(), /技术标准 PDF 本次未能成功获取/);
    await page.goto(url + "#c14");
    await page.waitForFunction(() => document.getElementById("c14").open);
    await page.locator("#c14 a[href='#f05']").first().click();
    await page.waitForFunction(() => document.getElementById("f05").open);
    assert.match(await page.locator("#f05 .prose").textContent(), /没有进行盲品/);
    await page.locator("#chapter-query").fill("C15");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c15");
    await page.waitForFunction(() => document.getElementById("c15").open);
    await page.locator("#c15 a[href='#f06']").click();
    await page.waitForFunction(() => document.getElementById("f06").open);
    assert.match(await page.locator("#f06 .prose").textContent(), /没有实地评估任何街区/);
    await page.goto(url + "#e02");
    await page.waitForFunction(() => document.getElementById("e02").open);
    await page.locator("#e02 a[href='#n03']").click();
    await page.waitForFunction(() => document.getElementById("n03").open);
    assert.match(await page.locator("#n03 .prose").textContent(), /德国为 49.7%/);
    await page.goto(url + "#c01");
    await page.waitForFunction(() => document.getElementById("c01").open);
    assert.match(await page.locator("#c01 .prose").textContent(), /想要一个晚上，别总被劝成五分钟/);
    await page.locator("#chapter-query").fill("C16");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c16");
    await page.waitForFunction(() => document.getElementById("c16").open);
    assert.match(await page.locator("#c16 .prose").textContent(), /镜子里的合适，与身体里的合适/);
    await page.locator("#c16 a[href='#f08']").click();
    await page.waitForFunction(() => document.getElementById("f08").open);
    assert.match(await page.locator("#f08 .prose").textContent(), /没有取得并完整审核 ISO 标准原文/);
    await page.goto(url + "#c17");
    await page.waitForFunction(() => document.getElementById("c17").open);
    await page.locator("#c17 a[href='#b07']").click();
    await page.waitForFunction(() => document.getElementById("research-content").open);
    await page.locator("#research-content a[href='#n07']").click();
    await page.waitForFunction(() => document.getElementById("n07").open);
    assert.match(await page.locator("#n07 .prose").textContent(), /不是长期幸福或整个制作过程的愉快程度/);
    await page.goto(url + "#c18");
    await page.waitForFunction(() => document.getElementById("c18").open);
    await page.locator("#c18 a[href='#n08']").click();
    await page.waitForFunction(() => document.getElementById("n08").open);
    assert.match(await page.locator("#n08 .prose").textContent(), /实际享受的交互 F < 1/);
    await page.locator("#chapter-query").fill("C19");
    assert.equal(await page.locator(".chapter-intro:visible").count(), 1);
    await page.goto(url + "#c19");
    await page.waitForFunction(() => document.getElementById("c19").open);
    assert.match(await page.locator("#c19 .prose").textContent(), /输赢与选择质量，可以分开看/);
    await page.locator("#c19 a[href='#f09']").click();
    await page.waitForFunction(() => document.getElementById("f09").open);
    await page.goto(url + "#c19");
    await page.locator("#c19 a[href='#n09']").click();
    await page.waitForFunction(() => document.getElementById("n09").open);
    assert.match(await page.locator("#n09 .prose").textContent(), /不是 38,935 人都完成三轮/);
    await page.goto(url + "#c20");
    await page.waitForFunction(() => document.getElementById("c20").open);
    await page.locator("#c20 a[href='#f10']").first().click();
    await page.waitForFunction(() => document.getElementById("f10").open);
    await page.goto(url + "#c20");
    await page.locator("#c20 a[href='#n10']").click();
    await page.waitForFunction(() => document.getElementById("n10").open);
    assert.match(await page.locator("#n10 .prose").textContent(), /p = .058/);
    await page.locator("#essay-query").fill("E08");
    assert.equal(await page.locator(".argument:visible").count(), 1);
    await page.locator("#essay-query").fill("没有这个论点887765");
    assert.equal(await page.locator(".argument:visible").count(), 0);
    await page.goto(url + "#e07");
    await page.waitForFunction(() => document.getElementById("e07").open);
    assert.equal(await page.locator("#essay-query").inputValue(), "");
    await page.locator("#guide-query").fill("P010");
    assert.equal(await page.locator(".playbook:visible").count(), 1);
    await page.goto(url + "#p010");
    await page.waitForFunction(() => document.getElementById("p010").open);
    assert.equal(await page.locator("#p010 .prose details").count(), 4);
    assert.equal(await page.locator("#p010 .prose details[open]").count(), 0);
    await page.locator("#p010 .prose details > summary").first().click();
    assert.equal(await page.locator("#p010 .prose details[open]").count(), 1);
    await page.locator("#guide-query").fill("不存在的玩法887");
    await page.goto(url + "#p001");
    await page.waitForFunction(() => document.getElementById("p001").open);
    assert.equal(await page.locator("#guide-query").inputValue(), "");
    await page.goto(url + "#n04");
    await page.waitForFunction(() => document.getElementById("n04").open);
    await page.locator("#query").fill("J019");
    assert.equal(await page.locator(".card:visible").count(), 1);
    await page.locator("#query").fill("没有这个关键词987654");
    assert.equal(await page.locator(".card:visible").count(), 0);
    assert.equal(await page.locator("#random").isDisabled(), true);
    assert.equal(await page.locator("#empty").isVisible(), true);
    await page.locator("#reset").click();
    await page.locator("#minutes").selectOption("20");
    await page.locator("#budget").selectOption("0");
    await page.locator("#company").selectOption("solo");
    await page.locator("#energy").selectOption("low");
    const matching = await page.locator(".card:visible").evaluateAll(items => items.map(x => x.dataset));
    assert(matching.length > 0);
    matching.forEach(x => {
      assert(Number(x.minutes) <= 20 && Number(x.budget) === 0);
      assert(["solo", "either"].includes(x.company) && x.energy === "low");
    });
    await page.locator("#random").click();
    assert(await page.evaluate(() => document.activeElement.tagName === "SUMMARY"));
    await page.goto(url + "#j019");
    await page.waitForFunction(() => document.getElementById("j019").open);
    assert.equal(await page.locator("#j019").getAttribute("open"), "");
    await page.goto(url + "#b01");
    await page.waitForFunction(() => document.getElementById("research-content").open);
    assert.equal(await page.locator("#research-content").getAttribute("open"), "");
    await page.goto(url);
    await page.reload();
    await page.locator("#j019 > summary").focus();
    await page.keyboard.press("Enter");
    assert.equal(await page.locator("#j019").getAttribute("open"), "");
    await page.evaluate(() => scrollTo({top: 0, behavior: "instant"}));
    await page.screenshot({path: process.env.SCREENSHOT_DESKTOP || "/tmp/enjoythemoment-desktop.png", fullPage: false});
    await page.setViewportSize({width: 390, height: 844});
    await page.goto(url);
    await page.reload();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.goto(url + "#e04");
    await page.waitForFunction(() => document.getElementById("e04").open);
    await page.locator("#e04").evaluate(el => el.scrollIntoView({behavior: "instant", block: "start"}));
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path: "/tmp/enjoythemoment-essay-mobile.png", fullPage: false});
    await page.goto(url);
    await page.reload();
    await page.screenshot({path: process.env.SCREENSHOT_MOBILE || "/tmp/enjoythemoment-mobile.png", fullPage: false});
    await page.emulateMedia({colorScheme: "dark", reducedMotion: "reduce"});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.emulateMedia({media: "print"});
    await page.evaluate(() => dispatchEvent(new Event("beforeprint")));
    assert.equal(await page.locator("details:not([open])").count(), 0);
    assert.equal(errors.length, 0, JSON.stringify(errors));
    assert.equal(requests.length, 0, JSON.stringify(requests));
    const nojs = await browser.newContext({javaScriptEnabled: false, viewport: {width: 390, height: 844}});
    const staticPage = await nojs.newPage();
    await staticPage.goto(url);
    assert.equal(await staticPage.locator(".card").count(), 60);
    assert.equal(await staticPage.locator("#filters").isVisible(), false);
    assert.equal(await staticPage.locator("#essay-search-label").isVisible(), false);
    await staticPage.locator("#e07 > summary").click();
    assert.equal(await staticPage.locator("#e07 .prose").isVisible(), true);
    await staticPage.locator("#j001 > summary").click();
    assert.equal(await staticPage.locator("#j001 .card-body").isVisible(), true);
    await nojs.close();
    console.log("OK: offline, filters, empty state, deep links, keyboard, 390px, dark/reduced motion, print, no-JS, zero external requests");
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
